name: chw_admin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  firebase_storage: ^13.0.1
  firebase_database: ^12.0.1
  google_fonts: ^6.3.1
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.10.0
  provider: ^6.1.5+1
  intl: ^0.20.2
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  go_router: ^14.6.1
  cached_network_image: ^3.4.1
  flutter_staggered_grid_view: ^0.7.0
  table_calendar: ^3.1.2
  flutter_typeahead: ^5.2.0
  universal_html: ^2.2.4
  fl_chart: ^0.69.0
  file_picker: ^8.0.0+1
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icons/logo.jpeg
    - assets/icons/icon.png

# 🔹 Add this block for flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
  image_path: "assets/icons/icon.png"
