// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt-kqSnzsape6sI1h9LL4tga1XN0J235A',
    appId: '1:1027724937621:web:e4ca56308adf55fa4a8e9c',
    messagingSenderId: '1027724937621',
    projectId: 'community-health-a340d',
    authDomain: 'community-health-a340d.firebaseapp.com',
    storageBucket: 'community-health-a340d.firebasestorage.app',
    measurementId: 'G-HQ072Y40CW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5EMQ1N9-MHIOXg7BeJ3kf-cBUOocdFnI',
    appId: '1:1027724937621:android:3911a79dc336d4074a8e9c',
    messagingSenderId: '1027724937621',
    projectId: 'community-health-a340d',
    storageBucket: 'community-health-a340d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCez8temkEsx83iUQCBDl3AlCOhfDhsa0k',
    appId: '1:1027724937621:ios:e49a58127dba1c454a8e9c',
    messagingSenderId: '1027724937621',
    projectId: 'community-health-a340d',
    storageBucket: 'community-health-a340d.firebasestorage.app',
    iosBundleId: 'com.example.chwAdmin',
  );
}
